tags:
    -   name: users
        description: users API

paths:
    # [GET] users
    /users:
        get:
            tags:
                - users
            summary: Find All Users
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

        # [POST] users
        post:
            tags:
                - users
            summary: Add User
            parameters:
                -   name: body
                    in: body
                    description: user Data
                    required: true
                    schema:
                        $ref: '#/definitions/users'
            responses:
                201:
                    description: 'Created'
                400:
                    description: 'Bad Request'
                409:
                    description: 'Conflict'
                500:
                    description: 'Server Error'

    # [GET] users/id
    /users/{id}:
        get:
            tags:
                - users
            summary: Find User By Id
            parameters:
                -   name: id
                    in: path
                    description: User Id
                    required: true
                    type: integer
            responses:
                200:
                    description: 'OK'
                409:
                    description: 'Conflict'
                500:
                    description: 'Server Error'

        # [PUT] users/id
        put:
            tags:
                - users
            summary: Update User By Id
            parameters:
                -   name: id
                    in: path
                    description: user Id
                    required: true
                    type: integer
                -   name: body
                    in: body
                    description: user Data
                    required: true
                    schema:
                        $ref: '#/definitions/users'
            responses:
                200:
                    description: 'OK'
                400:
                    description: 'Bad Request'
                409:
                    description: 'Conflict'
                500:
                    description: 'Server Error'

        # [DELETE] users/id
        delete:
            tags:
                - users
            summary: Delete User By Id
            parameters:
                -   name: id
                    in: path
                    description: user Id
                    required: true
                    type: integer
            responses:
                200:
                    description: 'OK'
                409:
                    description: 'Conflict'
                500:
                    description: 'Server Error'

# definitions
definitions:
    Users:
        type: object
        required:
            - email
            - password
            - name
        properties:
            email:
                type: string
                description: user Email
            password:
                type: string
                description: user Password
            name:
                type: string
                description: user name
    Event:
        type: object
        required:
            - name
            - id
        properties:
            name:
                type: string
                description: the event's Name
            id:
                type: string
                description: the event's uuid
            shoppingList:
                type: array
                description: list of thing to buy for the event
            budgetManager:
                type: object
                description: budgetManager of the event
            playlist:
                type: array
                description: playlist of the event
            participants:
                type: array
                description: list of all the participants to the event
    BudgetManager:
        type: object
        required:
            - id
        proprieties:
            id:
                type: string
                description: uuid
            total:
                type: number
                description: the total of all the spendings
            spendings:
                type: array
                description: all the spendings linked to the budget manager



schemes:
    - https
    - http
