---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: clever-party-thrower
  replicas: 3
  template:
    metadata:
      labels:
        app: clever-party-thrower
    spec:
      containers:
        - name: clever-party-thrower
          image: nginx:alpine
          ports:
            - containerPort: 80
