---
apiVersion: v1
kind: Service
metadata:
  name: clever-party-thrower
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: clever-party-thrower
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
