# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test back-end on github and push on docker-hub

on:
  push:
    branches:
      - "*"

jobs:
  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        continue-on-error: true
        run: |
          set +e
          npm audit
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Warning: npm audit found packages that need to be fixed."
          fi
          set -e
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint Nest.js app
        run: npm run lint
  build:
    needs: [ audit, lint ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Nest.js app
        run: npm run build

  Test_Back-end_unit:
    needs: [ build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    services:
      postgres:
        image: postgis/postgis

        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PSW}}
          POSTGRES_USER: ${{vars.DATABASE_USER}}
          POSTGRES_DB: ${{vars.TEST_DATABASE_NAME}}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use variables
        run: |
          echo "DATABASE_HOST variable : ${{ vars.DATABASE_HOST }}"
          echo "DATABASE_USER variable : ${{ vars.DATABASE_USER }}"
          echo "TEST_DATABASE_NAME variable : ${{ vars.TEST_DATABASE_NAME }}"
          echo "JWT_AUTH_TTL variable : ${{ vars.JWT_AUTH_TTL }}"
          echo "JWT_REFRESH_TTL variable : ${{ vars.JWT_REFRESH_TTL }}"

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: build project
        run: npm run build

      - name: Run the unit tests suites
        run: npm run test -- src/dept/utils/debts.utils.spec.ts src/email.service.spec.ts
        #        run: npm run test
        env:
          TEST_DATABASE_NAME: ${{vars.TEST_DATABASE_NAME}}
          DATABASE_HOST: ${{vars.DATABASE_HOST}}
          DATABASE_PORT: ${{vars.DATABASE_PORT}}
          DATABASE_USER: ${{vars.DATABASE_USER}}
          DATABASE_PSW: ${{secrets.DATABASE_PSW}}
          DATABASE_NAME: ${{vars.DATABASE_NAME}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
          JWT_AUTH_TTL: ${{vars.JWT_AUTH_TTL}}
          JWT_REFRESH_TTL: ${{vars.JWT_REFRESH_TTL}}
          EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          TWO_FACTOR_AUTHENTICATION_APP_NAME: ${{vars.TWO_FACTOR_AUTHENTICATION_APP_NAME}}
          EMAIL_VERIFICATION_URL: ${{vars.EMAIL_VERIFICATION_URL}}

  #      - name: Run the e2e tests suites
  #        #        run: npm run test -- src/dept/utils/debts.utils.spec.ts
  #        run: npm run test:e2e
  #        env:
  #          TEST_DATABASE_NAME: ${{vars.TEST_DATABASE_NAME}}
  #          DATABASE_HOST: ${{vars.DATABASE_HOST}}
  #          DATABASE_PORT: ${{vars.DATABASE_PORT}}
  #          DATABASE_USER: ${{vars.DATABASE_USER}}
  #          DATABASE_PSW: ${{secrets.DATABASE_PSW}}
  #          DATABASE_NAME: ${{vars.DATABASE_NAME}}
  #          JWT_SECRET: ${{secrets.JWT_SECRET}}
  #          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
  #          JWT_AUTH_TTL: ${{vars.JWT_AUTH_TTL}}
  #          JWT_REFRESH_TTL: ${{vars.JWT_REFRESH_TTL}}
  #          TWO_FACTOR_AUTHENTICATION_APP_NAME: ${{vars.TWO_FACTOR_AUTHENTICATION_APP_NAME}}
  Test_Back-end_integration:
    needs: [ build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    services:
      postgres:
        image: postgis/postgis

        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PSW}}
          POSTGRES_USER: ${{vars.DATABASE_USER}}
          POSTGRES_DB: ${{vars.TEST_DATABASE_NAME}}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use variables
        run: |
          echo "DATABASE_HOST variable : ${{ vars.DATABASE_HOST }}"
          echo "DATABASE_USER variable : ${{ vars.DATABASE_USER }}"
          echo "TEST_DATABASE_NAME variable : ${{ vars.TEST_DATABASE_NAME }}"
          echo "JWT_AUTH_TTL variable : ${{ vars.JWT_AUTH_TTL }}"
          echo "JWT_REFRESH_TTL variable : ${{ vars.JWT_REFRESH_TTL }}"

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: build project
        run: npm run build

      #      - name: Run the unit tests suites
      #        run: npm run test -- src/dept/utils/debts.utils.spec.ts
      #        #        run: npm run test
      #        env:
      #          TEST_DATABASE_NAME: ${{vars.TEST_DATABASE_NAME}}
      #          DATABASE_HOST: ${{vars.DATABASE_HOST}}
      #          DATABASE_PORT: ${{vars.DATABASE_PORT}}
      #          DATABASE_USER: ${{vars.DATABASE_USER}}
      #          DATABASE_PSW: ${{secrets.DATABASE_PSW}}
      #          DATABASE_NAME: ${{vars.DATABASE_NAME}}
      #          JWT_SECRET: ${{secrets.JWT_SECRET}}
      #          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
      #          JWT_AUTH_TTL: ${{vars.JWT_AUTH_TTL}}
      #          JWT_REFRESH_TTL: ${{vars.JWT_REFRESH_TTL}}
      #          TWO_FACTOR_AUTHENTICATION_APP_NAME: ${{vars.TWO_FACTOR_AUTHENTICATION_APP_NAME}}

      - name: Run the backend integration tests suites
        #        run: npm run test -- src/dept/utils/debts.utils.spec.ts
        run: npm run test:integr
        env:
          TEST_DATABASE_NAME: ${{vars.TEST_DATABASE_NAME}}
          DATABASE_HOST: ${{vars.DATABASE_HOST}}
          DATABASE_PORT: ${{vars.DATABASE_PORT}}
          DATABASE_USER: ${{vars.DATABASE_USER}}
          DATABASE_PSW: ${{secrets.DATABASE_PSW}}
          DATABASE_NAME: ${{vars.DATABASE_NAME}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
          JWT_AUTH_TTL: ${{vars.JWT_AUTH_TTL}}
          JWT_REFRESH_TTL: ${{vars.JWT_REFRESH_TTL}}
          EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          TWO_FACTOR_AUTHENTICATION_APP_NAME: ${{vars.TWO_FACTOR_AUTHENTICATION_APP_NAME}}
          EMAIL_VERIFICATION_URL: ${{vars.EMAIL_VERIFICATION_URL}}
  Build_docker_image_of_back-end:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    needs: [ Test_Back-end_unit, Test_Back-end_integration ]
    defaults:
      run:
        working-directory: ./back-end
        # only if the app build and test successfully

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clever-party-thrower-back-end:latest
  Push_build_to_docker_hub:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    needs: [ Test_Back-end_unit, Test_Back-end_integration, Build_docker_image_of_back-end ]
    defaults:
      run:
        working-directory: ./back-end
        # only if the app build and test successfully

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clever-party-thrower-back-end:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/clever-party-thrower-back-end:latest

#  Update_and_restart_docker_container_versions_on_remote:
#    name: Deploy To Cluster
#    runs-on: ubuntu-latest
#    needs: [ Build_and_push_docker_image_of_back-end ]
#    steps:
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
