name: Compile LaTeX Document

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: .
          extra_packages: texlive-latex-extra texlive-bibtex-extra texlive-science
          run: |
            latexmk -pdf -synctex=1 -interaction=nonstopmode -file-line-error -halt-on-error main.tex
            bibtex main
            makeglossaries main
            latexmk -pdf -synctex=1 -interaction=nonstopmode -file-line-error -halt-on-error main.tex
            latexmk -c

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: compiled-report
          path: main.pdf
